server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mariadb://112.217.238.122:3306/okrbsc?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&passwordCharacterEncoding=UTF-8
    url: jdbc:mariadb://119.203.225.10:3306/board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&passwordCharacterEncoding=UTF-8
#    username: anyfive
#    password: anyfive
    username: maria
    password: maria

# http://119.203.225.10:8080

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
